language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - pypy

#install: pip install gitpython
install: pip install -r requirements.txt
# # command to run tests, e.g. python setup.py test
script: python setup.py test
notifications:
   on_success: change
   on_failuer: always
